### ISSUE TITLE
Make Footer Stick to Bottom of Page

### ISSUE THREAD

**Issue by Bibo-Joshi** [AkaBlas/akalisten#18]
I tried a Few things to get that done, but it always involved setting `body.min-height = 100vh` and that alwyas introduced a scrollbar for me. I'd liked to avoid that …

**Comment by fscholdei** [comment]
100vh means that it will be exactly as tall as the browser window. If a margin has been set somewhere or the block does not start at the very beginning of the page, this can result in a scrollbar.

What does _stick to bottom_ mean?

Basically, you can do the following:

```css
body {
   margin-bottom: 25px; /* choose large enough so that the footer does not overlap the last section on the page */
}
footer {
   position: sticky; /* or `fixed` if the text should always appear at the very bottom */
   bottom: 0;
}
```

However, I wonder why that would make sense. With the accordions collapsed, the text would always be legible and the content can't be so important that it has to permanently force itself into the user's field of view.

Or do you mean that the footer should not be placed next to the actual content but below it with an appropriate distance? But what should happen when everything is unfolded?
